# Generated by Django 3.2.6 on 2022-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Country chicken', 'Country Chicken'), ('Poultry chicken', 'Poultry chicken'), ('Mutton', 'Mutton'), ('Fish seafood ', 'Fish seafood'), ('Prawns', 'Prawns'), ('Cold cuts', 'Cold cuts'), ('Ready to cook', 'Ready to cook'), ('Deal of the day', 'Deal of the day')], max_length=100)),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
        ),
    ]
