# Generated by Django 3.2.6 on 2022-07-17 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20220717_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=242)),
                ('locality', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('total_price', models.FloatField()),
                ('Address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Others', 'Others')], default='Home', max_length=25)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('payment_mode', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=200, null=True)),
                ('order_date', models.DateField()),
                ('order_time', models.DateField(null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
