# Generated by Django 3.2.6 on 2022-05-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Deal of the day', 'Deal of the day'), ('Country chicken', 'Country Chicken'), ('Poultry chicken', 'Poultry chicken'), ('Mutton', 'Mutton'), ('Fish seafood ', 'Fish seafood'), ('Prawns', 'Prawns'), ('Cold cuts', 'Cold cuts'), ('Ready to cook', 'Ready to cook')], max_length=100),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('pieces', models.CharField(max_length=100, null=True)),
                ('product_image', models.ImageField(upload_to='producting')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
