# Generated by Django 3.2.6 on 2022-05-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220523_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
