# Generated by Django 3.2.6 on 2022-05-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pieces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
