# Generated by Django 3.2.6 on 2022-07-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ordeitem_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdeItem',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
