# Generated by Django 3.2.6 on 2022-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220524_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Deal_of_the_day', 'Deal_of_the_day'), ('Country_chicken', 'Country_Chicken'), ('Poultry_chicken', 'Poultry_chicken'), ('Mutton', 'Mutton'), ('Fish_seafood ', 'Fish_seafood'), ('Prawns', 'Prawns'), ('Cold_cuts', 'Cold_cuts'), ('Ready_to_cook', 'Ready_to_cook')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Deal_of_the_day', 'Deal_of_the_day'), ('Country_chicken', 'Country_Chicken'), ('Poultry_chicken', 'Poultry_chicken'), ('Mutton', 'Mutton'), ('Fish_seafood ', 'Fish_seafood'), ('Prawns', 'Prawns'), ('Cold_cuts', 'Cold_cuts'), ('Ready_to_cook', 'Ready_to_cook')], max_length=100),
        ),
    ]
