# Generated by Django 3.2.6 on 2022-07-18 09:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
