# Generated by Django 3.2.6 on 2022-07-20 18:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_no',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Address_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('1', 'success'), ('2', 'failure'), ('3', 'pending')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='userprofile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Others', 'Others')], default='Home', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
