# Generated by Django 3.2.6 on 2022-07-21 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_auto_20220721_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=200, null=True)),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('order_date', models.DateField(null=True)),
                ('order_time', models.TimeField(null=True)),
                ('payment_status', models.CharField(choices=[('1', 'success'), ('2', 'failure'), ('3', 'pending')], max_length=50, null=True)),
                ('order_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('locality', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Others', 'Others')], default='Home', max_length=25, null=True)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='userprofile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='myapp.userprofile'),
        ),
    ]
