# Generated by Django 3.2.6 on 2022-07-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220721_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.userprofile'),
        ),
    ]
