# Generated by Django 3.2.6 on 2022-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvideo',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
