# Generated by Django 3.2.6 on 2022-07-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
