# Generated by Django 3.2.6 on 2022-07-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myapp.userprofile'),
        ),
    ]
